### ISSUE TITLE
run pip install for example installing requests

### ISSUE THREAD

**Issue by sea5kg** [opensource-unigine-plugins/unigine-2.14-editor-plugin-python3scripting#13]
Possible same problem here:

https://stackoverflow.com/questions/60619799/undefined-symbol-error-with-embedded-python-interpreter

Plugin must be loaded with `RTLD_GLOBAL`

But now problem is:

```

ERROR. Python3Scripting: WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Python3Scripting: Defaulting to user installation because normal site-packages is not writeable

Python3Scripting: Collecting requests

Python3Scripting:   Using cached requests-2.31.0-py3-none-any.whl (62 kB)

Python3Scripting: Collecting idna<4,>=2.5

Python3Scripting:   Using cached idna-3.4-py3-none-any.whl (61 kB)

Python3Scripting: Collecting charset-normalizer<4,>=2

Python3Scripting:   Downloading charset_normalizer-3.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)

ERROR. Python3Scripting: ERROR: Exception:
Traceback (most recent call last):
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 366, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 212, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 140, in __bool__
    return any(self)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
    super().__init__(
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 305, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/network/download.py", line 143, in __call__
    chunks = _prepare_download(resp, link, self._progress_bar)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/network/download.py", line 68, in _prepare_download
    return DownloadProgressProvider(progress_bar, max=total_length)(chunks)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 250, in DownloadProgressProvider
    return BAR_TYPES[progress_bar][0](max=max).iter
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 165, in __init__
    super().__init__(*args, **kwargs)  # type: ignore
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 76, in __init__
    self.original_handler = signal(SIGINT, self.handle_sigint)
  File "/home/user/plugin//bin/plugins/Sea5kg/Python3Scripting/Python3Home/lib/python3.10/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
ERROR. Python3Scripting: WARNING: You are using pip version 21.2.4; however, version 23.2.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Script ended (2322 ms)
```

need make mode with "main thread run"

**Comment by sea5kg** [comment]
Before run editor:
```
export LD_LIBRARY_PATH="$SCRIPT_DIR/bin:$LD_LIBRARY_PATH"
export LD_PRELOAD=`pwd`/bin/plugins/Sea5kg/Python3Scripting/libSea5kgPython3Scripting_editorplugin_x64d.so
```

**Comment by sea5kg** [comment]
![изображение](https://github.com/unigine-plugins/Sea5kgPython3Scripting_editorplugin/assets/1695720/cb18ed63-9bda-4ca1-989c-bbf43b9f0973)

wow wow
